name: Django CI/CD

on:
  push:
    branches:
      - main  # Déclencher le workflow uniquement sur la branche principale

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.5'  # Version spécifique de Python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r back_end/requirements.txt

    - name: Collect static files
      env:
        DJANGO_SETTINGS_MODULE: back_end.settings  # Remplacez par vos paramètres si différents
      run: |
        python back_end/manage.py collectstatic --noinput  # Collecte des fichiers statiques pour la production

  test:
    runs-on: ubuntu-latest
    needs: build  # Ce job s'exécute uniquement si le job 'build' réussit
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.5'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r back_end/requirements.txt

    - name: Run unit tests in audit/tests
      run: |
        python back_end/manage.py test audit.tests  # Exécuter les tests unitaires dans audit/tests.py

  deploy:
    runs-on: ubuntu-latest
    needs: test  # Ce job s'exécute uniquement si le job 'test' réussit
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.5'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r back_end/requirements.txt

    - name: Deploy to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        heroku git:remote -a etnauditapi
        git remote set-url heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/etnauditapi.git
        git push heroku main
      
