name: Django CI/CD

on:
  push:
    branches:
      - main  # Déclencher le workflow uniquement sur la branche principale

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.5'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit tests in audit/tests
      run: |
        python manage.py test audit.tests  # Exécuter les tests unitaires dans le dossier audit/tests

    - name: Lint code
      run: |
        pip install flake8
        flake8 .  # Vérification du linting pour assurer la qualité du code

    - name: Deploy to Heroku
      if: success()  # Déploiement uniquement si les étapes précédentes réussissent
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        heroku git:remote -a etnauditapi
        git push heroku main
